Sound system
JesseDes/Aristotle pull request #43
Opened 2019-11-08 01:03 UTC by moogey

2019-11-09 18:46 UTC, Megan-VanHumbeck approved these changes
Great job!

2019-11-09 18:47 UTC, Megan-VanHumbeck requested changes
Please change to merge into Dev rather than Master

2019-11-09 22:20 UTC, Megan-VanHumbeck approved these changes

2019-11-14 06:18 UTC, Belize22 approved these changes
Seems to work as intended, although we should gather more audio resources to further test this feature with greater reliability.

2019-11-14 06:18 UTC, merged